name: Process-plugin-version-test

on:
  workflow_dispatch:
    inputs:
      plugin:
        description: 'Plugin name'
        type: string
        required: true
      pluginversion:
        description: 'Plugin version'
        type: string
        required: true
      downloadurl:
        description: 'Plugin download URL'
        type: string
        required: true
      moodlebranch:
        description: 'Moodle branch'
        type: string
        required: true
      phpversion:
        description: 'PHP version'
        type: string
        required: true
      database:
        description: 'Database type (mariadb or postgres)'
        type: string
        default: mariadb

jobs:
  process-version:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          path: catalog

      - name: Test step
        run: |
          echo "---------------------------"
          echo "Plugin-input: ${{ github.event.inputs.plugin }}"
          echo "Plugin version: ${{ github.event.inputs.pluginversion }}"
          echo "---------------------------"
